### ISSUE TITLE
tests: have a workflow test for drone

### ISSUE THREAD

**Issue by masfaraud** [Dessia-tech/dessia_common#111]
No test for module workflow:
Maybe move a workflow to model to import?

**Comment by GhislainJ** [comment]
I think that _models/workflows/forms_workflows_ can be used. Its basically the same as former _workflow_with_models_

**Comment by GhislainJ** [comment]
Right now, we have some workflows being tested during CI exec. I think this can be closed but feel free to reopen if there is more to add to this
