### ISSUE TITLE
WorkflowRun: add method to plot in plot_data the different displays in a workflow 

### ISSUE THREAD

**Issue by Launayl** [Dessia-tech/dessia_common#115]
In a workflow Run it's can be useful to have a method to plot the different displays (Multiplot, ScatterPlot, ParralelPlot etc...) belong to the workflow
![Capture d’écran du 2021-10-14 15-04-21](https://user-images.githubusercontent.com/61781433/137324193-dcdd3782-67d1-4a41-8c10-b38fecd5ccc2.png)

**Comment by GhislainJ** [comment]
This is deprecated since the changes for display blocks
