### ISSUE TITLE
Support Any typing

### ISSUE THREAD

**Issue by GhislainJ** [Dessia-tech/dessia_common#125]
**Note: for support questions, please use https://nextcloud.dessia.tech/call/hr9z9bif

* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request

* **What is the current behavior?**
Any from builtin module _typing_ is not supported

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages

* **What is the expected behavior?**
Any **could** be supported. Do we want to support it ? We expose ourselves to users "Anying" everything

* **What is the motivation / use case for changing the behavior?**

Workflow classes can sometimes use generic functions. We tried to implement it more lately. 
In the case of add_input_value of WorkflowState, it could work as well, but its `value` arg should be typed Any, which is not supported by dessia_common

* **Possible fixes**
Maybe we could alias it but it would be difficult.
We should add a specific jsonschema item for Any. How do we implement it frontend side ?

* **Please tell us about your environment:**
  
  - branch: master
  - commit:  
  - python version: 3.9

**Comment by Tanguylo** [comment]
It is done, so do we close this ?

**Comment by GhislainJ** [comment]
This has not been done entirely but isn't this relevant anymore. Any typing cannot be understood by frontend anyway so its use should not be promoted

**Comment by GhislainJ** [comment]
Will be removed by schema refactor
