### ISSUE TITLE
increase test coverage of vectored_objects

### ISSUE THREAD

**Issue by masfaraud** [Dessia-tech/dessia_common#147]
Vectored objects is the worst tracked module in test coverage (32%)
2 compatible options:
- Add tests for uncoverd methods
- remove useless code

**Comment by GhislainJ** [comment]
Increased to 51% with not really robust tests.

I think we could remove the Objective stuff as it is not used I think or the whole module

**Comment by Tanguylo** [comment]
Obsolete ?

**Comment by GhislainJ** [comment]
> Obsolete ?

I think it is. Should we remove vectored_objects implementation & support ? I think so

**Comment by GhislainJ** [comment]
Vectored objects to be removed
