### ISSUE TITLE
BinaryFile

### ISSUE THREAD

**Issue by ilanbricaud** [Dessia-tech/dessia_common#152]
**Note: for support questions, please use https://nextcloud.dessia.tech/call/hr9z9bif
 @GhislainJ @masfaraud

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request

* **What is the current behavior?**
The platform doesn't support the type dessia_common.files.BinaryFile.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages
- select a workflow that requires step files as an input
- provide step files
- click run

* **What is the expected behavior?**
read step files

* **What is the motivation / use case for changing the behavior?**
read step files

* **Possible fixes**

* **Please tell us about your environment:**
  
  - branch: tests_platform
  - commit:  the last one I guess
  - python version: 3.8.10

![Capture d’écran du 2022-01-11 17-23-29](https://user-images.githubusercontent.com/89774048/148981396-854846e0-9c82-4ee0-98f7-09f44855e90c.png)

**Comment by ladnane** [comment]
thanks for the report, this is a backend issue, a ticket is already created for this new feature. will update ASAP.
https://gitea.dessia.tech/DessiA/dessia-platform-backend/issues/281

**Comment by GhislainJ** [comment]
@ladnane @ilanbricaud Has this been solved on backend side ?

**Comment by ilanbricaud** [comment]
@GhislainJ it would seem so, but only @ladnane can comfirm

**Comment by ladnane** [comment]
yes this was fixed. am closing the issue.
