### ISSUE TITLE
Serialization/breakdown

### ISSUE THREAD

**Issue by MackJoly** [Dessia-tech/dessia_common#230]
**Note: for support questions, please use https://nextcloud.dessia.tech/call/hr9z9bif

* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request

* **What is the current behavior?**

[Ticket attached in platform testing]
I try to open a workflow run and it wouldn't with an error 500
Here is the log from plateform : 

195742 ERROR   :app              : [21/Apr/2022 13:36:57] : Exception on /objects/dessia_common.workflow.core.WorkflowRun/62615bf6b3a87d897243f377 [GET]
195743 Traceback (most recent call last):
195744   File "/usr/local/lib/python3.9/dist-packages/dessia_common/utils/serialization.py", line 160, in deserialize
195745     return dict_to_object(serialized_element, global_dict=global_dict,
195746   File "/usr/local/lib/python3.9/dist-packages/dessia_common/utils/serialization.py", line 259, in dict_to_object
195747     obj = class_(**subobjects)
195748 TypeError: __init__() missing 1 required positional argument: 'points'
195749
195750 During handling of the above exception, another exception occurred:
195751
195752 Traceback (most recent call last):
195753   File "/usr/local/lib/python3.9/dist-packages/dessia_common/breakdown.py", line 43, in extract_from_object
195754     return object_[int(segment)]
195755 ValueError: invalid literal for int() with base 10: 'variable_values'
195756
195757 During handling of the above exception, another exception occurred:
195758
195759 Traceback (most recent call last):
195760   File "/var/www/platform-packages/dessia_platform_backend/models/engineering.py", line 766, in _instantiate_python_object_from_dict
195761     python_object = self.python_class.dict_to_object(self.object_dict)
195762   File "/usr/local/lib/python3.9/dist-packages/dessia_common/workflow/core.py", line 1359, in dict_to_object
195763     pointers_memo.update(dereference_jsonpointers(dict_))
195764   File "/usr/local/lib/python3.9/dist-packages/dessia_common/utils/serialization.py", line 485, in dereference_jsonpointers
195765     pointers_memo[ref] = deserialize(serialized_element=serialized_element,
195766   File "/usr/local/lib/python3.9/dist-packages/dessia_common/utils/serialization.py", line 168, in deserialize
195767     return dict_to_object(serialized_element)
195768   File "/usr/local/lib/python3.9/dist-packages/dessia_common/utils/serialization.py", line 210, in dict_to_object
195769     pointers_memo.update(dereference_jsonpointers(dict_))
195770   File "/usr/local/lib/python3.9/dist-packages/dessia_common/utils/serialization.py", line 484, in dereference_jsonpointers
195771     serialized_element = get_in_object_from_path(dict_, ref)
195772   File "/usr/local/lib/python3.9/dist-packages/dessia_common/breakdown.py", line 66, in get_in_object_from_path
195773     element = extract_from_object(element, segment)
195774   File "/usr/local/lib/python3.9/dist-packages/dessia_common/breakdown.py", line 56, in extract_from_object
195775     raise NotImplementedError(f'Cannot extract segment {segment} from object {object_}')
195776 NotImplementedError: Cannot extract segment variable_values from object {'name': '', 'object_class': 'volmdlr.wires.ClosedPolygon3D', 'package_version': '0.4.0', 'color': None, 'alpha': 1, 'line_segments': [{'object_class': 'volmdlr.edges.LineSegment3D', 'name': '', 'start': {'object_class': 'volmdlr.Point3D', 'x': -0.12, 'y': 0.23800000000000002, 'z': 0.484, 'name': ''}, 'end': {'object_class': 'volmdlr.Point3D', 'x': -0.11495840471991865, 'y': 0.23800000000000002, 'z': 0.4926361054319561, 'name': ''}}, {'object_class': 'volmdlr.edges.LineSegment3D', 'name': '', 'start': {'object_class': 'volmdlr.Point3D', 'x': -0.11495840471991865, 'y': 0.23800000000000002, 'z': 0.4926361054319561, 'name': ''}, 'end': {'object_class': 'volmdlr.Point3D', 'x': -0.11495840471991865, 'y': 0.20800000000000002, 'z': 0.4926361054319561, 'name': ''}}, {'object_class': 'volmdlr.edges.LineSegment3D', 'name': '', 'start': {'object_class': 'volmdlr.Point3D', 'x': -0.11495840471991865, 'y': 0.20800000000000002, 'z': 0.4926361054319561, 'name': ''}, 'end': {'object_class': 'volmdlr.Point3D', 'x': -0.11344592613589426, 'y': 0.20800000000000002, 'z': 0.4952269370615429, 'name': ''}}, {'object_class': 'volmdlr.edges.LineSegment3D', 'name': '', 'start': {'object_class': 'volmdlr.Point3D', 'x': -0.11344592613589426, 'y': 0.20800000000000002, 'z': 0.4952269370615429, 'name': ''}, 'end': {'object_class': 'volmdlr.Point3D', 'x': -0.12, 'y': 0.193, 'z': 0.484, 'name': ''}}, {'object_class': 'volmdlr.edges.LineSegment3D', 'name': '', 'start': {'object_class': 'volmdlr.Point3D', 'x': -0.12, 'y': 0.193, 'z': 0.484, 'name': ''}, 'end': {'object_class': 'volmdlr.Point3D', 'x': -0.12, 'y': 0.23800000000000002, 'z': 0.484, 'name': ''}}], 'primitives': [{'$ref': '#/variable_values/(1, 1, 0)/html_output/primitives/14/contour3d/line_segments/0'}, {'$ref': '#/variable_values/(1, 1, 0)/html_output/primitives/14/contour3d/line_segments/1'}, {'$ref': '#/variable_values/(1, 1, 0)/html_output/primitives/14/contour3d/line_segments/2'}, {'$ref': '#/variable_values/(1, 1, 0)/html_output/primitives/14/contour3d/line_segments/3'}, {'$ref': '#/variable_values/(1, 1, 0)/html_output/primitives/14/contour3d/line_segments/4'}]}
195777
195778 During handling of the above exception, another exception occurred:
195779
195780 Traceback (most recent call last):
195781   File "/var/www/platform-packages/flask/app.py", line 2447, in wsgi_app
195782     response = self.full_dispatch_request()
195783   File "/var/www/platform-packages/flask/app.py", line 1952, in full_dispatch_request
195784     rv = self.handle_user_exception(e)
195785   File "/var/www/platform-packages/flask_cors/extension.py", line 165, in wrapped_function
195786     return cors_after_request(app.make_response(f(*args, **kwargs)))
195787   File "/var/www/platform-packages/flask/app.py", line 1821, in handle_user_exception
195788     reraise(exc_type, exc_value, tb)
195789   File "/var/www/platform-packages/flask/_compat.py", line 39, in reraise
195790     raise value
195791   File "/var/www/platform-packages/flask/app.py", line 1950, in full_dispatch_request
195792     rv = self.dispatch_request()
195793   File "/var/www/platform-packages/flask/app.py", line 1936, in dispatch_request
195794     return self.view_functions[rule.endpoint](**req.view_args)
195795   File "/var/www/platform-packages/dessia_platform_backend/routes/__init__.py", line 112, in active_user_function
195796     return function(*args, **kwargs)
195797   File "/var/www/platform-packages/flask_limiter/extension.py", line 705, in __inner
195798     return obj(*a, **k)
195799   File "<string>", line 2, in get_object
195800   File "/var/www/platform-packages/pony/orm/core.py", line 519, in new_func
195801     result = func(*args, **kwargs)
195802   File "/var/www/platform-packages/dessia_platform_backend/routes/objects.py", line 458, in get_object
195803     json_value = obj.to_json(
195804   File "/var/www/platform-packages/dessia_platform_backend/models/engineering.py", line 697, in to_json
195805     dict_['export_formats'] = self.export_formats()
195806   File "/var/www/platform-packages/dessia_platform_backend/models/engineering.py", line 653, in export_formats
195807     elif hasattr(self.python_object, '_export_formats'):
195808   File "/var/www/platform-packages/dessia_platform_backend/models/engineering.py", line 585, in python_object
195809     self._python_object = self._instantiate_python_object_from_dict()
195810   File "/var/www/platform-packages/dessia_platform_backend/models/engineering.py", line 776, in _instantiate_python_object_from_dict
195811     json.dump(d, err_file)
195812   File "/usr/lib/python3.9/json/__init__.py", line 179, in dump
195813     for chunk in iterable:
195814   File "/usr/lib/python3.9/json/encoder.py", line 431, in _iterencode
195815     yield from _iterencode_dict(o, _current_indent_level)
195816   File "/usr/lib/python3.9/json/encoder.py", line 405, in _iterencode_dict
195817     yield from chunks
195818   File "/usr/lib/python3.9/json/encoder.py", line 405, in _iterencode_dict
195819     yield from chunks
195820   File "/usr/lib/python3.9/json/encoder.py", line 438, in _iterencode
195821     o = _default(o)
195822   File "/usr/lib/python3.9/json/encoder.py", line 179, in default
195823     raise TypeError(f'Object of type {o.__class__.__name__} '
195824 TypeError: Object of type BinaryFile is not JSON serializable

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Possible fixes**

* **Please tell us about your environment:**
  
  - branch: master
  - commit:  
  - python version:

**Comment by masfaraud** [comment]
may be fixed by https://github.com/Dessia-tech/dessia_common/commit/d6b0239b2d7bec29cf66fad228215d092feaea92

**Comment by MackJoly** [comment]
I add something to this ticket, here is new error when i click on a wfrun

--- Logging error ---
399753 Traceback (most recent call last):
399754   File "/usr/local/lib/python3.9/dist-packages/dessia_common/breakdown.py", line 43, in extract_from_object
399755     return object_[int(segment)]
399756 ValueError: invalid literal for int() with base 10: 'faces'
399757
399758 The above exception was the direct cause of the following exception:
399759
399760 Traceback (most recent call last):
399761   File "/usr/local/lib/python3.9/dist-packages/dessia_common/breakdown.py", line 71, in get_in_object_from_path
399762     element = extract_from_object(element, segment)
399763   File "/usr/local/lib/python3.9/dist-packages/dessia_common/breakdown.py", line 56, in extract_from_object
399764     raise ValueError(f'Cannot extract segment {segment} from object {object_}') from error

**Comment by masfaraud** [comment]
this is a volmldlr problem
