### ISSUE TITLE
pb deserializing new files types

### ISSUE THREAD

**Issue by AdnaneOnFire** [Dessia-tech/dessia_common#240]
* **Please tell us about your environment:**
  - platform: platform-testing
  - branch: fix/displat-settings
  - commit:  c9aaa4f412b08233bdec9e190309699ec2e08a58
  - python version: 

error during workflow run due to unsupported file types deserialization:

```
Traceback (most recent call last):\n File \"/var/www/platform-packages/dessia_platform_backend/routes/jobs.py\", line 253, in submit_job\n arguments = obj.python_object.dict_to_arguments(\n File \"/usr/local/lib/python3.9/dist-packages/dessia_common/workflow/core.py\", 
line 638, in dict_to_arguments\n deserialized_value = deserialize_argument(type_=input_.type_, argument=value)\n File \"/usr/local/lib/python3.9/dist-packages/dessia_common/utils/serialization.py\", 
line 377, in deserialize_argument\n raise TypeError(\"Deserialization of ype {} is Not Implemented\".format(type_))\nTypeError: Deserialization of ype <class 'dessia_common.files.BinaryFile'> is Not Implemented\n
```

**Comment by GhislainJ** [comment]
If I am not mistaken, this has been solved on testing, but fix/display-settings only communicates with master so it doesn't see the changes

When this PR https://github.com/Dessia-tech/dessia_common/pull/239 is merged we can merge it back on testing and have the two fixes

**Comment by AdnaneOnFire** [comment]
I still created a small PR to handle handle valid subclasses of files (BinaryFile and StringFile)
