### ISSUE TITLE
Problem with references in case of custom eq

### ISSUE THREAD

**Issue by masfaraud** [Dessia-tech/dessia_common#273]
Redefining eq of an object may create side effects in serialization.
Subobjects may not be equal strictly but can be pointed outside of the object, and won't be in the memo

solution: when an object is matched in the memo, keep exploring its subattributes in case they are used elsewhere

**Comment by masfaraud** [comment]
Would it be a python eq problem?

**Comment by GhislainJ** [comment]
Has this been solved ?
