### ISSUE TITLE
How to use Display/Export Block

### ISSUE THREAD

**Issue by MackJoly** [Dessia-tech/dessia_common#280]
**Note: for support questions, please use https://nextcloud.dessia.tech/call/hr9z9bif

* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request

* **What is the current behavior?**
When i added a block display in my workflow, i did not really understand what is the parameter : order
I filled it with multiple value but nothing really worked
Same thing when i try to use a method export zip with a Export block

* **Please tell us about your environment:**
  
  - branch: dev
  - commit:  latest
  - python version:

**Comment by GhislainJ** [comment]
Order input should not be implemented anymore
