### ISSUE TITLE
workflow run : reference error when saving in data base

### ISSUE THREAD

**Issue by younesdessia** [Dessia-tech/dessia_common#329]
**Note: for support questions, please use https://nextcloud.dessia.tech/call/hr9z9bif

* **I'm submitting a ...**
  - [X ] bug report
  - [ ] feature request

* **What is the current behavior?**
When I running the Workflow in platform testing.ovh, some models have been saved in db but he give me an error and i don't get the workflow run. check_platform works well in local, for the same workflow run.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages
* 
I got this error for two workflow when I try to run him  in the platform quoted above. (one of them is workflow tuto2 power_transmission, which is easy to manipulate to recreate the error)

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Possible fixes**

* **Please tell us about your environment:**
  
  - branch: master 
  - commit:  11afeb8e91f140c8396cfc27b5171ddda5a5d5a9
  - python version: Python 3.8.10

![Capture d’écran du 2022-08-11 16-33-37](https://user-images.githubusercontent.com/109952534/184158534-e8c321c9-29f6-40f5-9593-ccc3a9ec2e45.png)

**Comment by younesdessia** [comment]
Lucas

**Comment by GhislainJ** [comment]
@younesdessia This should be fixed on dev branch. Merging it back on testing then master is blocked for now as it requires tha backend on dev as well, which is not being merged right now
