### ISSUE TITLE
A volmdlr (geomdl) object considered as list_iterator object

### ISSUE THREAD

**Issue by sbendjebla** [Dessia-tech/dessia_common#335]
**Note: for support questions, please use https://nextcloud.dessia.tech/call/hr9z9bif

* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request

* **What is the current behavior?**
When a WF is run, it gives **Failure** in 0 seconds, with these errors:
![image](https://user-images.githubusercontent.com/68638483/186642383-db948f84-6c79-4a8c-876e-f410ab6ef220.png)

Actually, `self.surface`, which is a geomdl `BsplineSurface`, is considered as `list_iterator` object. So, we can't use `evaluate_single` method.

Giving **Faillure** quickly is strange, because, I've added some prints, but they are not displayed during running (which takes 0 seconds)

ps. I have this problem only on the platform. In local Spyder script, everything is OK.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Possible fixes**

* **Please tell us about your environment:**
  
  - branch: 
  - commit:  
  - python version:

**Comment by GhislainJ** [comment]
Closing this because it has been idle for a long time
