### ISSUE TITLE
Rename HeterogeneousList

### ISSUE THREAD

**Issue by masfaraud** [Dessia-tech/dessia_common#384]
If there is no HomogenousList
Ideas:
* DessiaList
* ObjectList
* ObjectContainer

List can be confusing

**Comment by Tanguylo** [comment]
I'm ok with DessiaList and I propose:
- DataSet (the best one for me, redundant with plot_data, but plot_data will be refactored soon)
- DessiaTable
- ItemList (same as ObjectList ?)
- DessiaSet (not cool to hear)
-
