### ISSUE TITLE
Question : dessiaobject.to_xlsx - no extension - normal ?

### ISSUE THREAD

**Issue by MackJoly** [Dessia-tech/dessia_common#407]
**Note: for support questions, please use https://nextcloud.dessia.tech/call/hr9z9bif

* **I'm submitting a ...**
  - Question

* **What is the current behavior?**
I exported a class inheritent from DessiaObject and I applied .to_xlsx. No extension is mentioned on the file, should it be automatic or the user has to write the extension ?

  
  - branch: dev
  - commit:  
  - python version: 3.9.13

**Comment by GhislainJ** [comment]
Hi @MackJoly ,
ExportFormats are currently being refactored. I include you remarks in my checklist and I'll get back to you when I have more hindsight on it

**Comment by MackJoly** [comment]
Perfect, thank you for your answer ! Feel free to close the issue, I forced the extension and it works well

**Comment by GhislainJ** [comment]
That's an "ok way" to do it, I guess, but the extension should be set automatically, I think
