### ISSUE TITLE
 python script is not faithful to the workflow

### ISSUE THREAD

**Issue by younesdessia** [Dessia-tech/dessia_common#411]
**Note: for support questions, please use https://nextcloud.dessia.tech/call/hr9z9bif

* **I'm submitting a ...**
  - [X] feature request

* **What is the current behavior?**
When we load the .py workflow from the platform, the script is not faithful to the workflow

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages
to reproduce this comportement you can load .py from the platform (a somewhat complex workflow)

* **What is the expected behavior?**
Have a script .py with the same blocs that we have in the platform

* **What is the motivation / use case for changing the behavior?**
Download the script to use it localy or to push it in another dessia platform

* **Possible fixes**

* **Please tell us about your environment:**
  
  - branch: master
  - commit:  last
  - python version: 3.8

**Comment by xavier-ferry** [comment]
After a small private talk : 

1. There is an issue if the workflow is composed of only 1 block and that this block is a workflowblock which has pipes. 
The subworkflow does not ask to import the Pipe class and the fact that the workflow does not have pipes implies that, in the end, we lack the Pipe import.

2. There is not enough details for us to understand the problem or even **if** there is a problem. This issue has to be clarified. We are waiting for your feedback @younesdessia @DumouchelP

**Comment by younesdessia** [comment]
@xavier-ferry if we import the script of the workflow, we get variables with same name, if we push this script we got problem in the workflow (platform).
[dessia_common.workflow.core.Workflow_6360769080b2eeba7b7fa5da (1).py.txt](https://github.com/Dessia-tech/dessia_common/files/9918758/dessia_common.workflow.core.Workflow_6360769080b2eeba7b7fa5da.1.py.txt)
