### ISSUE TITLE
Numpy is used but not in requirements

### ISSUE THREAD

**Issue by GhislainJ** [Dessia-tech/dessia_common#424]
**Note: for support questions, please use https://nextcloud.dessia.tech/call/hr9z9bif

* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request

* **What is the current behavior?**

Pycharm just warned me that numpy is used in utils/diff.py but is not declared as a requirement.

Should we keep it and set it in setup or should we get reed of it ?
Its there to ensure numpy equalities

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Possible fixes**

* **Please tell us about your environment:**
  
  - branch: 
  - commit:  
  - python version:

**Comment by masfaraud** [comment]
Imported via scipy -> numpy, but ok to explicitely import

**Comment by GhislainJ** [comment]
I think we now use numpy directly into the code as we import it in some modules

**Comment by GhislainJ** [comment]
Related to #454
