### ISSUE TITLE
Export error

### ISSUE THREAD

**Issue by younesdessia** [Dessia-tech/dessia_common#453]
**Note: for support questions, please use https://nextcloud.dessia.tech/call/hr9z9bif

* **I'm submitting a ...**
  - [X] bug report

* **What is the current behavior?**
an error is returned on the exports (py, json...)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages
Use last version of dessia_comman, dev branch

* **What is the expected behavior?**
see export buttons

* **What is the motivation / use case for changing the behavior?**

* **Possible fixes**

* **Please tell us about your environment:**
  
  - branch: dev
  - commit: 
  - python version: 3.8

![image](https://user-images.githubusercontent.com/109952534/207030963-fe526608-84e0-425e-bde0-96b6de11b125.png)

`751095	TypeError: Type is not JSON serializable: ExportFormat
751096	
751097	During handling of the above exception, another exception occurred:
751098	
751099	Traceback (most recent call last):
751100	  File "/var/www/platform-packages/flask/app.py", line 2525, in wsgi_app
751101	    response = self.full_dispatch_request()
751102	  File "/var/www/platform-packages/flask/app.py", line 1822, in full_dispatch_request
751103	    rv = self.handle_user_exception(e)
751104	  File "/var/www/platform-packages/flask_cors/extension.py", line 165, in wrapped_function
751105	    return cors_after_request(app.make_response(f(*args, **kwargs)))
751106	  File "/var/www/platform-packages/flask/app.py", line 1820, in full_dispatch_request
751107	    rv = self.dispatch_request()
751108	  File "/var/www/platform-packages/flask/app.py", line 1796, in dispatch_request
751109	    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
751110	  File "/var/www/platform-packages/dessia_platform_backend/routes/__init__.py", line 108, in active_user_function
751111	    return function(*args, **kwargs)
751112	  File "/var/www/platform-packages/flask_limiter/extension.py", line 1152, in __inner
751113	    R, flask.current_app.ensure_sync(cast(Callable[P, R], obj))(*a, **k)
751114	  File "/var/www/platform-packages/dessia_platform_backend/routes/objects.py", line 1012, in export_formats
751115	    return jsonify(obj.export_formats())
751116	  File "/var/www/platform-packages/flask/json/__init__.py", line 342, in jsonify
751117	    return current_app.json.response(*args, **kwargs)
751118	  File "/var/www/platform-packages/flask/json/provider.py", line 309, in response
751119	    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
751120	  File "/var/www/platform-packages/flask/json/provider.py", line 230, in dumps
751121	    return json.dumps(obj, **kwargs)
751122	  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
751123	    return cls(
751124	  File "/var/www/platform-packages/dessia_platform_backend/app.py", line 193, in encode
751125	    return json.dumps(obj)
751126	  File "/usr/lib/python3.9/json/__init__.py", line 231, in dumps
751127	    return _default_encoder.encode(obj)
751128	  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
751129	    chunks = self.iterencode(o, _one_shot=True)
751130	  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
751131	    return _iterencode(o, 0)
751132	  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
751133	    raise TypeError(f'Object of type {o.__class__.__name__} '
751134	TypeError: Object of type ExportFormat is not JSON serializable`

**Comment by GhislainJ** [comment]
@younesdessia You'll probably need the new version of the backend. I am unsure on which branch the fix is available, though, on testing, surely. What branch are you on for the backend ?
