### ISSUE TITLE
Modules not listed in setup.py

### ISSUE THREAD

**Issue by GhislainJ** [Dessia-tech/dessia_common#454]
Some packages are used but not listed in setup.py. Here is a non exhaustive list : 

- Numpy
- pylint
- orjson
- networkx
- (plot_data)
- (volmdlr)
- ...

Should they be added ?

**Comment by masfaraud** [comment]
pylint is a dev dependency

**Comment by GhislainJ** [comment]
This is actually a bug from pycharm that has never been issued
