### ISSUE TITLE
deserialization Error

### ISSUE THREAD

**Issue by younesdessia** [Dessia-tech/dessia_common#467]
**Note: for support questions, please use https://nextcloud.dessia.tech/call/hr9z9bif

* **I'm submitting a ...**
  - [X] bug report

* **What is the current behavior?**
* 
I have an object A `Component` which has as parameter frame_origin, on this object I have no problem, but on an object B `Assembly_component` which has as parameter object `A` I have a problem with the parameter fram_origin

also, in the workflow_run display we have this Assembly_component object and we have no problem there, but when we go to the library and open it I have this error.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Possible fixes**

* **Please tell us about your environment:**
  
  - branch: master
  - commit:  
  - python version: 3.8
  
`ERROR   :objects          : [21/Dec/2022 17:12:17] : deserialization of renault_custom.layout.layout_3d.AssemblyComponent 63a33d24d48e1ac6a45ea28f: Cannot get segment frame_origin from path #/frame_origin in element {'object_class': 'renault_custom.layout.layout_3d.AssemblyComponent', 'package_version': '0.0.3.dev412', 'name': 'Wf10_test_change_20_12', 'log': None, 'i_ground': 0, 'update_position': True, 'lx': 0.9379082058497836, 'ly': 1.3408953347954868, 'lz': 1.0235780578773777, 'components': [{'object_class': 'renault_custom.layout.layout_3d.Component', 'package_version': '0.0.3.dev412', 'name': 'env_box', 'log': None, 'alpha': 0.4, 'volume_model_input': {'object_class': 'volmdlr.core.VolumeModel', 'pack
566569	Traceback:
566570	Traceback (most recent call last):
566571	  File "/usr/local/lib/python3.9/dist-packages/dessia_common/breakdown.py", line 95, in get_in_object_from_path
566572	    element = extract_segment_from_object(element, segment)
566573	  File "/usr/local/lib/python3.9/dist-packages/dessia_common/breakdown.py", line 74, in extract_segment_from_object
566574	    raise ExtractionError(message_error)
566575	dessia_common.breakdown.ExtractionError: Cannot extract segment frame_origin from object {'object_class': 'renault_custom.layout.layout_3d.AssemblyComponent', 'package_version': '0.0.3.dev412', 'name': 'Wf10_test_change_20_12', 'log': None, 'i_ground': 0, 'update_position': True, 'lx': 0.9379082058497836, 'ly': 1.3408953347954868, 'lz': 1.0235780578773777, 'components': [{'object_class': 'renault_custom.layout.layout_3d.Component', 'package_version': '0.0.3.dev412', 'name': 'env_box', 'log': None, 'alpha': 0.4, 'volume_model_input': {'object_class': 'volmdlr.core.VolumeModel', 'pack`

**Comment by GhislainJ** [comment]
Backend link to track the issue : 
https://gitea.dessia.tech/DessiA/dessia-platform-backend/issues/687
