### ISSUE TITLE
non block variable with imposed value

### ISSUE THREAD

**Issue by younesdessia** [Dessia-tech/dessia_common#528]
**Note: for support questions, please use https://nextcloud.dessia.tech/call/hr9z9bif

* **I'm submitting a ...**
  - [ ] bug report
  - [X] feature request

* **What is the current behavior?**
Have the possibility to put a nbv with a default value using workflow builder.
tell me if I put an issue on another package.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Possible fixes**

* **Please tell us about your environment:**
  
  - branch: 
  - commit:  
  - python version:

**Comment by GhislainJ** [comment]
No real version needed here because it was done on frontend and didn't require any dessia_common change.
Frontend version :  0.23.0
