### ISSUE TITLE
Typing for load_from_stream of DessiaObject

### ISSUE THREAD

**Issue by DumouchelP** [Dessia-tech/dessia_common#557]
**Note: for support questions, please use https://nextcloud.dessia.tech/call/hr9z9bif

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request

* **What is the current behavior?**
No typing on load_from_stream class_method and no possibility to use on workflow builder

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages

* **What is the expected behavior?**
Need typing to use load_from_stream class_method of DessiaObject (VolumeModel) on the workflow builder

* **What is the motivation / use case for changing the behavior?**

* **Possible fixes**

* **Please tell us about your environment:**
  
  - branch: dev
  - commit:  
  - python version:

**Comment by younesdessia** [comment]
@DumouchelP it's on dev

**Comment by younesdessia** [comment]
@masfaraud you can close this issue too
