### ISSUE TITLE
Keeping references in serialization/deserialization

### ISSUE THREAD

**Issue by masfaraud** [Dessia-tech/dessia_common#6]
**Note: for support questions, please use https://nextcloud.dessia.tech/call/hr9z9bif

* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request

* **What is the current behavior?**
to_dict and dict to object does not keep references of objects. This is not a problem with object with equality based on data but for the other yes.
For graph based objects, we are forced to custom dict and dict_to_objects

* **Possible fixes**
- use json pointers in to_dict when an object is seen several times in serialization
- interpret these pointers in deserialization

**Comment by GhislainJ** [comment]
What is the status on this ? Is this considered done with the json_pointers features ?
