### ISSUE TITLE
Platform - when [] is output_value of a WorkflowRun

### ISSUE THREAD

**Issue by MackJoly** [Dessia-tech/dessia_common#67]
**Note: for support questions, please use https://nextcloud.dessia.tech/call/hr9z9bif

* **I'm submitting a ...**
  - [ ] bug report
  - [X] feature request

* **What is the current behavior?**
When there is no output_value, no display are available and some errors appears in consol section.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages

* **What is the expected behavior?**
An informing message that there is no solution

* **What is the motivation / use case for changing the behavior?**
I am affraid that customer won't understand the actual behavior

* **Possible fixes**

* **Please tell us about your environment:**
  
  - branch: 
  - commit:  
  - python version:

**Comment by GhislainJ** [comment]
After thinking about it, this is better just being frontend
